version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    container_name: newpick-mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newpick
      - MYSQL_ROOT_HOST=%
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mysql_network

  app:
    build:
      context: .
    container_name: newpick-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001 
      - DATABASE_URL=mysql://root:root@newpick-mysql:3306/newpick
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - app_network


volumes:
  mysql_data:

networks:
  mysql_network:
    name: mysql_network
    driver: bridge